version: "3.9"

services:
  db:
    image: postgres
    container_name: "notes-postgres"
    ports:
      - ${PSQL_PORT}:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: ${PSQL_USERNAME}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always